export default
{
    Alerts: "التنبيهات",
    Bold: "عريض",
    Chats: "المحادثات",
    ColorThemes: "أنماط اللون",
    Confirmation: "تأكيد",
    CopyRight: "جميع الحقوق محفوظة 2003-{0} فيت سوفت",
    Email: "البريد الإلكتروني",
    Error: "خطأ",
    ExtraLarge: "كبير جدا",
    Font: "الخط",
    FontSize: "حجم الخط",
    FontStyle: "نمط الخط",
    FontWeight: "وزن الخط",
    ForgetPassword: "هل نسيت كلمة المرور?",
    Information: "استفسار",
    Italic: "مائل",
    LIGHT: "لايت",
    Language: "اللغة",
    Large: "كبير",
    Medium: "متوسط",
    Normal: "عادي",
    PRIMARY: "أساسي",
    PRIMARY_DARK: "Primary Dark",
    Password: "كلمة المرور",
    Question: "سؤال",
    SECONDARY_BLUE: "Secondary Blue",
    SECONDARY_LIGHT: "Secondary Light",
    Settings: "الإعدادات",
    SignIn: "تسجيل دخول",
    SignOut: "تسجيل خروج",
    Small: "صغير",
    Splash: "سبلاش",
    Success: "نجاح",
    Text: "النص",
    UserName: "اسم المستخدم",
    VetSoft: "فيت سوفت",
    Warning: "تحذير",
    WarningMsg: "تحذير !",
    InternetConnection: "الاتصال بالإنترنت",
    Required: "من فضلك أدخل '{0}'",
    UserNamePlaceholderMessage:"من فضلك أدخل اسم المستخدم",
    PasswordPlaceholderMesssage:"من فضلك أدخل كلمة المرور",
    AuthenticationFailed:"فشلت المصادقة",
    InvalidLogin:"خطأ في اسم المستخدم أو كلمة المرور",
    EmptyData:"البيانات فارغة",
    OfflineMessage:"أنت غير متصل بالإنترنت",
    WrongMessage:"حدث خطأ ما , من فضلك قم بإغلاق التطبيق ثم أعد تشغيله!",
    Arabic : "عربي",
    English : "إنجليزي",
    Profile:"الملف الشخصي",
    LongTimeMessage:"هذه العملية أخذت وقا طويلا, من فضلك تأكد من الاتصال بالشبكة أو أعد المحاولة في وقت لاحق."
}