export default
{
    Alerts: "Alerts",
    Bold: "Bold",
    Chats: "Chats",
    ColorThemes: "Color Themes",
    Confirmation: "Confirmation",
    CopyRight: "Copyright @ 2003-{0} VetSoft",
    Email: "Email",
    Error: "Error",
    ExtraLarge: "Very Large",
    Font: "Font",
    FontSize: "Font Size",
    FontStyle: "Font Style",
    FontWeight: "Font Weight",
    ForgetPassword: "Forget Password",
    Information: "Information",
    Italic: "Italic",
    LIGHT: "Light",
    Language: "Language",
    Large: "Large",
    Medium: "Medium",
    Normal: "Normal",
    PRIMARY: "Primary",
    PRIMARY_DARK: "Primary Dark",
    Password: "Password",
    Question: "Question",
    SECONDARY_BLUE: "Secondary Blue",
    SECONDARY_LIGHT: "Secondary Light",
    Settings: "Settings",
    SignIn: "Sign in",
    SignOut: "Sign Out",
    Small: "Small",
    Splash: "Splash",
    Success: "Success",
    Text: "Text",
    UserName: "User Name",
    VetSoft: "VetSoft",
    Warning: "Warning",
    WarningMsg: "Warning !",
    InternetConnection: "Internet Connection",   
    Required: "Please provide '{0}'",
    UserNamePlaceholderMessage:"Enter Your User Name",
    PasswordPlaceholderMesssage:"Enter Your Password",
    AuthenticationFailed:"Authentication Failed",
    InvalidLogin:"Invalid Login Name or Password",
    EmptyData:"Data is empty",
    OfflineMessage:"You are offline",
    WrongMessage:"Soething was wrong, please restart the app!",
    Arabic : "Arabic",
    English : "English",
    Profile :"Profile",
    LongTimeMessage:"This action is taking a long time , Please check your network or try again later."
}